### ISSUE TITLE
DomTerm freezes when using sudo

### ISSUE THREAD

**Issue by mcarans** [PerBothner/DomTerm#102]
If I start DomTerm, then do `sudo xed`, type my password, then press CTRL-Z, then DomTerm freezes - I am not usually able to type my next command eg. `bg`.

**Comment by PerBothner** [comment]
This time it does look like a flow control problem, with the following in the log:

     [2021/07/28 14:24:35:4501] I: [2021/07/28 14:24:35:4501] I: session 1 paused (flow control) 268435454 bytes ahead sent:546 confirmed:548

**Comment by mcarans** [comment]
I also get freezing without sudo if I run some docker build commands. Let's see if any fix that you come up for the sudo problem will also fix the docker building.

**Comment by PerBothner** [comment]
This should fix the problem:

[ctrl-pause-patch.txt](https://github.com/PerBothner/DomTerm/files/6897906/ctrl-pause-patch.txt)

Doing `fg` leads to some awkward echoing.

**Comment by mcarans** [comment]
Yes that fixed it. Thanks for investigating!

**Comment by mcarans** [comment]
Closing as seems to be working fine
