### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by artemgur** [PerBothner/DomTerm#107]
Can I remap the interrupt from "Ctrl+C" to some other keys using settings.ini? I want to do that as a more radical solution to Ctrl+C copy vs interrupt question.

And can I disable the focus on the menu on Alt press? When I switch keyboard layouts with Alt+Shift, I sometimes press Alt earlier than Shift. It causes the menu to focus and next key presses do actions in the menu. Because of that, I accidentally exited domterm multiple times, when I wanted to type 'q' letter after switching keyboard layouts.

**Comment by PerBothner** [comment]
_"Can I remap the interrupt from "Ctrl+C" to some other keys using settings.ini?"_

In principle, but there are some complications.  You probably want to change the interrupt character in the terminal driver (perhaps using `stty intr X` where `X` is the other character). Alternatively, it may be fairly easy to add a command that sends an interrupt directly.

What bindings did you have in mind?

_"And can I disable the focus on the menu on Alt press?"_

This may be something your browser/front-end is doing.  I don't see "focus on the menu" on Alt press.  Which browser/front-end are you using? Which OS?

**Comment by artemgur** [comment]
_"And can I disable the focus on the menu on Alt press?"_

Yes, that's actually an issue of Electron.

**Comment by artemgur** [comment]
_"Can I remap the interrupt from "Ctrl+C" to some other keys using settings.ini?"_

I have Ctrl+N in mind, because as far as I know it's used neither in stty nor in domterm.

The problem is that when I remap interrupt to something else, Ctrl+C stops working as interrupt in domterm, but the new binding doesn't work as interrupt in domterm.

copy-text-or-interrupt from [the docs](https://domterm.org/Keyboard-shortcuts.html) would be good enough, but now it doesn't work as intended.

In the first terminal in a new window prompt Ctrl+C works as copy.
After I hit Enter to execute the first command, Ctrl+C works as a plain interrupt. Both during the execution of the first command, and in all prompts and commands after that (including other tabs).

**Comment by PerBothner** [comment]
You can change the interrupt key to:

    stty intr ^N

and in `settings.ini` do:

    keymap.line-edit =
     | "Ctrl+N": client-action
    keymap.master =
     | "Ctrl+N": client-action

At least it seems to work ...

**Comment by artemgur** [comment]
Yes, that works. Thank you :)
