### ISSUE TITLE
domterm 2.9.4 --port doesn't work and is very serious security issue

### ISSUE THREAD

**Issue by psb777** [PerBothner/DomTerm#119]
I downloaded the 2.9.4 AppImage.
I'm running Devuan Daedalus (i.e. Debian Bookworm without systemd) on my desktop
There:
`$ domterm --port 8080 new /bin/bash`
On a local browser (uptodate Chrome)
`http://localhost:8080`
gives blank screen (i.e. no bash interaction)
and
`http://localhost:8080/etc/passwd`
displays /etc/passwd file

Note that `$ domterm new /bin/bash` works.

**Comment by PerBothner** [comment]
Hmmm. The "server" (i.e. `--port`) feature has clearly gotten a bit bit-rotted.  I'm looking into it.

If I want to run a terminal in Firefox (for example), I normally just do:
```
domterm -Bfirefox
```
Combining a `port` specification with a `new` command should probably be an error. The `new` should happen implicitly when you browse to `http://localhost:8080`. That used to work, but got broken at some point.

Interpreting `http://localhost:8080/etc/passwd` as "return the contents of `etc/passwd`" is a bug. However, it's not clear to me that there is a "very serious security issue" - more than creatng a terminal would be.  If you create a terminal in a browser, that terminal has the permissions of the user that started the server.  And that user can read `/etc/passwd`. That said, the documentation should be much clearer that you be very careful about starting a listener, doubly so on a multi-user system or if the port is publicly accessible.

It would probably a good idea for the documentation to include a recipe for how to set things up so the terminal session starts with a login prompt. If you have a suggestion, it would welcome.

**Comment by PerBothner** [comment]
I fixed the "security issue" part of the bug report. I.e. the http server will no longer respond with local files unless the request contains a matching randomly generated server key.

The fix is in the github sources.  I'll upload a new AppImage after I fixed the `--port` feature not working.

**Comment by PerBothner** [comment]
I've commited some fixes so `--port` works again. There are still some issues: the `--port` feature needs some polishing. It is not the "normal" way of using domterm. If you have a use case for domterm-as-a-service I'll be happy to work on the necessary polishing, but I need to have a better understanding of the use-case.

I still haven't updated the documentation or the AppImage.

**Comment by PerBothner** [comment]
I'm aware of the shell-in-a-box project, without having looked closely at it.  Is that the sort of functionality you're looking for?

**Comment by psb777** [comment]
Hello! Thanks for responding. Understanding the use case?

If
`$ domterm new /path/command args`
has a use case then so must(!)
`$ domterm --port 8080 new /path/command args` 
I do not understand why one of those should be considered "normal" and the other in any way unusual. Let me tell you about this thing called the Internet  :-)

I would like to use domterm remotely just like one can use it so well locally but here are my two immediate
use cases:
   - I have an old fashioned plain text console/terminal interactive app. 
   - I have a few very clever Unix-style filters which extracts/parses very useful information out of plain text.

These I would like to expose to new users on the web. 

I tried to use shell-in-a-box and abandoned it for a reason I can no longer remember. But even were I to get it it to work "domterm" is better, or would be!  I have tried so many of the supposed solutions to this problem and they all (it seems to me) have issues. The only one (I've been able to get working) requires a ssh login and this extra layer is entirely unnecessary. It's wssh confusingly renamed to webssh (at least one other thing called webssh exists) and it can be found here `https://pypi.org/project/webssh/`

I like domterm very much. The docs read as if anything possible locally should be possible remotely. If there's a quick fix I would really appreciate it. Thanks for all your good work!

**Comment by psb777** [comment]
`http://localhost:8080/etc/passwd` - the reason this is a security bug is that `http://remotehost.com:8080/etc/passwd` also works.

**Comment by psb777** [comment]
Here is an interesting (I think) "service" which I've made available via the Python webssh/wssh. The intervening ssh is entirely unnecessary and itself provides a security problem in that a general ssh login screen can easily be provoked to appear: 
[Chatbots using OpenAI's GPT via TuneGPT](https://beardsell.com/ai/tunegpt)

This would be somewhat nicer were it enabled by domterm.

**Comment by PerBothner** [comment]
To use domterm in basic shell-in-box mode, running `CMD ARGS`, do:
```
domterm --port NNN shell.default='CMD ARGS'
```
