### ISSUE TITLE
Drop support for xulapp?

### ISSUE THREAD

**Issue by rwhogg** [PerBothner/DomTerm#12]
Mozilla has announced plans to deprecate XUL. From [their blog](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/):

> Consequently, we have decided to deprecate add-ons that depend on XUL, XPCOM, and XBL. We don’t have a specific timeline for deprecation, but most likely it will take place within 12 to 18 months from now.

Granted that DomTerm isn't an "add-on" per se, but I can't see Mozilla putting in a lot of effort to maintain XUL when they're going full steam ahead towards replacing it. So IMO it might be wise not to bother making an XUL version of DomTerm any more.

**Comment by rwhogg** [comment]
Closing because I discovered that you're already aware of the issue.

**Comment by PerBothner** [comment]
Note that at this point xulapp has the nicest user interface: menubar, context menu, copy and paste working as desired.   The JavaFX/WebView version is close, and could be readily improved, but there are issues, not least that JavaFX isn't getting a lot of resources. Also XUL/Firefox is a better-behaved Free Software citizen - for example it is available in the standard Fedora repository, which is not the case for Chrome/Chromium or JavaFX.

**Comment by rwhogg** [comment]
> The JavaFX/WebView version is close, and could be readily improved, but there are issues, not least that JavaFX isn't getting a lot of resources. Also XUL/Firefox is a better-behaved Free Software citizen - for example it is available in the standard Fedora repository, which is not the case for Chrome/Chromium or JavaFX.

Agreed. 

One other point - I didn't realize at first that the Firefox app and the XUL app were the same thing. (The fact there is both "run-firefox" and "run-xul" confused me). I thought at first that the Firefox app was an "Open Web App" (or whatever Mozilla's decided to call them these days).

Sorry for wasting your time on this issue.

**Comment by PerBothner** [comment]
I added some comments to Makefile.in to clarify difference between run-xul and run-firefox.

**Comment by ajsb85** [comment]
Mozilla going to deprecate XPCOM and XUL for add-ons.
Firefox, Thunderbird, Nightingale, Instantbird, Komodo need XUL and XPCOM to work.
The deprecation is for add-ons no for apps...

**Comment by PerBothner** [comment]
Assuming the Servo experiment works out, I expect XUL and XPCOM will be phased out for stand-alone applications as well. Look at [browser.html](https://github.com/browserhtml/browserhtml) as a prototype.
