### ISSUE TITLE
Please find Christ and/or Nix

### ISSUE THREAD

**Issue by aidan-gibson** [PerBothner/DomTerm#120]
I tried variants of your build instructions on four different OS' and couldn't get a build. This is a deep shame because this seems like fantastic software more people should be using. Please take a day to produce some functioning releases; it seems like you put a lot of work into this and again it's a deep shame there aren't any functioning releases out.

**Comment by PerBothner** [comment]
Be more specific. Which OS is did you try; what did you try to do (which commands did you use); and how did things fail.

**Comment by PerBothner** [comment]
Probably spam. No actionable issue.
