### ISSUE TITLE
Custom terminfo

### ISSUE THREAD

**Issue by kbrock** [PerBothner/DomTerm#24]
I like your approach of providing as good a terminal as possible, while providing a mechanism for extending it. This is very cool.

I noticed that `xterm` and `iTerm2` (mac) provide their own terminfo entries.
iTerm2 even had a command for generating a terminfo file. This I thought was ingenious.

iTerm2 has some custom escape sequences like downloading files in-band.
I notice that you are adding some custom extensions like displaying an image inline. Have you considered registering these in terminfo as well? Or were you able to leverage an existing raster/vector standard and just use data urls?

I'm not sure if this request is even realistic. Maybe terminfo is a thing of the past. It is a nice promise to be able to advertise your capabilities and have programs discover them and how to call them. Providing an escape sequence to produce the terminfo file seems like a great idea as well.

**Comment by PerBothner** [comment]
Adding new capabilities (codes) to terminfo (i.e. "registering extensions in terminfo") seems infeasible. There is no mechanism or management for that.

Adding new terminal types to the terminto database is possible.  In fact the DomTerm sources include an entry for domterm - just set TERM=domterm and TERMINFO to the DomTerm directory.  See d/domterm and d/domterm.ti.

However, like most more-or-less-xterm-compatible terminal emulators, DomTerm by default sets TERM=xterm-256color. One reason is that TERM=domterm breaks if you ssh to a computer that doesn't have a domtem entry in its database.  Anyother is there is little point: At the level of terminfo capabilities, there isn't much difference between "xterm-compatible" terminals.  (Of course many of them, including DomTerm, have bugs in their xterm-compatibility.)

I know that Emacs instead does some probing, including sending a "Secondary Device Attributes (DA)" query" and interpreting the result (in an ad hoc manner).  See lisp/term/xterm.el.

I have considered implementing support for the Sixel protocol.  It's very simple, and some other terminal emulators support it. (The xterm source has support, though It may need to compiled or enabled in some way - it's not the default here on Fedora.)

**Comment by kbrock** [comment]
terminals were pretty revolutionary. But they have remained stagnant for years.

Html has proven itself very versatile for laying out text on the screen. While it is not ideal, it does allow many developers to customize it, even for other people's code. e.g. changing gmail's UI from a local javascript or css file.

So having html supported in the terminal would be great.

But there needs to be a mechanism where a program could discover what is available and leverage it. I had thought terminfo/termcap could provide this discovery mechanism.

From here, it seems that they would be able to update programs on a slower rate, leveraging these new features and falling back to basic text.


How did you see this playing out?

**Comment by PerBothner** [comment]
There is a mechanism to discover that a program running under DomTerm.
Basically, you can check the DOMTERM environment variable.

It would salo be reasonable to pick some suitable values for a "Secondary Device Attributes (DA)" to report. This is a triple of integers, so it shouldn't be difficult to find something (probably) unambiguous.

That does mean a program would have to specifically test for DomTerm, rather than testing for a specific functionality, as with terminfo. Maybe in the future HTML-based terminals will be more common, and we can standardize some escape sequences, but I don't see that happening anytime soon.

**Comment by PerBothner** [comment]
See [this page](http://domterm.org/Detecting-domterm-terminal.html) about how to detect DomTerm.
