### ISSUE TITLE
How do i change the font?

### ISSUE THREAD

**Issue by SolarAquarion** [PerBothner/DomTerm#38]

**Comment by PerBothner** [comment]
You can set a style rule like this:

     div.domterm-pre { font-family: monospace }
 
See the Styling section in the manual for to set a style rule.  For example you can add the following to `~/.domterm/settings.ini`:

    style.user=
     |div.domterm-pre { font-family: monospace }

It probably makes sense to add a stylesheet rule like we already do for say `--main-dark-color`, but I haven't done that yet.

**Comment by SolarAquarion** [comment]
this isn't in the Styling section

**Comment by PerBothner** [comment]
I agree this would make sense to add to Styling section - it's likely to be a relatively common request.

**Comment by PerBothner** [comment]
I added a `--monospace-family` CSS variable, so that is now the preferred way to change the font:

    div.domterm { --monospace-family: "FreeMono","DejaVu Sans Mono"}
I also updated the Styling section in the manual.

**Comment by PerBothner** [comment]
These was a bug in that column/row counts didn't get recalculated when stylesheets were updated (for example when reloading `settings.ini`).  I checked in a fix for that.
