### ISSUE TITLE
server.h:34:27: fatal error: libwebsockets.h: No such file or directory

### ISSUE THREAD

**Issue by aaronkilik** [PerBothner/DomTerm#41]
I compiled libwebsockets from source like this:
```
$cd ~/Downloads
$git clone https://github.com/warmcat/libwebsockets
$cd libwebsockets
$mkdir build
$cd build
$cmake -DLWS_WITH_SSL=0  ..
```
After running this command, which runs successfully from the DomTerm local repository:
`$./configure  --with-libwebsockets=~Downloads/libwebsockets/build/`

Then:
`$make`

I get the following error in the output of make:
```
In file included from server.c:2:0:
server.h:34:27: fatal error: libwebsockets.h: No such file or directory
```

Am using Ubuntu 16.04. Could you please help. Thanks in advance.

**Comment by PerBothner** [comment]
It looks like I replied to this issue, but only privately.  For the record:

There is a missing slash after '~': `--with-libwebsockets=~/Downloads/libwebsockets/build/`

Furthermore, your shell might not be doing tilde-expansion in the middle of a word (even after '='), so best to expand it:

     --with-libwebsockets=$HOME/Downloads/libwebsockets/build

**Comment by aaronkilik** [comment]
Oh yeah, running this actually worked:
`$ ./configure  --with-libwebsockets=$HOME/Downloads/libwebsockets/build`

I guess the problem was with tilde-expansion, after changing to $HOME, everything worked fine.

Thanks.
