### ISSUE TITLE
Sending Shift+Tab

### ISSUE THREAD

**Issue by egoisticalgoat** [PerBothner/DomTerm#44]
DomTerm doesn't seem to send Ctrl+Tab, and sends a normal Tab instead.

My current DomTerm commit: 5f2efbb (current master)

**Comment by PerBothner** [comment]
What should it send? I tried xterm and gnome-terminal, and they do the same.

**Comment by PerBothner** [comment]
Do you have (1) another terminal emulator that sends a different character sequence for ctrl+tab, and (2) an application that recognizes this control sequence?

**Comment by egoisticalgoat** [comment]
Sorry, i just noticed i got my buttons confused :man_facepalming: 
It's Shift+Tab, not Ctrl+Tab.

I've tried with zsh (switching through autocompletion), and micro (for decreasing indentation).

**Comment by PerBothner** [comment]
Please try the attached patch.

[tab-patch.txt](https://github.com/PerBothner/DomTerm/files/2115869/tab-patch.txt)

**Comment by egoisticalgoat** [comment]
That worked! It's working the same as in gnome-terminal now! 
Thank you!

**Comment by PerBothner** [comment]
Cool.  I pushed the fix.

**Comment by PerBothner** [comment]
Since you use zsh (at least on occasion), have you tried a DomTerm-aware prompt string? I'd be interested in your take on http://domterm.org/Shell-prompts.html#zsh-shell-prompt .

(I don't think I have a direct email for you.)

**Comment by egoisticalgoat** [comment]
I've just tried it, it's definitely better than my attempt at understanding the escape sequences and building the prompt string myself :grinning: 
But I'm not entirely sure what the ` \e]75;> \a` does? And there's an `\e[14u`, so shouldn't there be a `\e[13u` too (if i understand your [documentation](https://domterm.org/Wire-byte-protocol.html) correctly)? 

And you can always send me a mail @ pascal(dot)pirschel(at)gmail(dot)com

**Comment by PerBothner** [comment]
The documentation for `\e15u` does say it it implicitly ends a prompt.  It would probably be helpful to mention it under `\e13u`.  And more generally clarify the different ways to end a prompt.
The `\e]75;> \a` looks like an error - I think it should be `\e]122l> \a` which specifies a "continuation prompt pattern" - a not-yet-checked-in feature to support multi-line input editing areas.  It specifies (will specify) how to generate a prompt for lines after the first (like PS2).
