### ISSUE TITLE
domterm.org is acting weird for Russian-speaking clients

### ISSUE THREAD

**Issue by yamnikov-oleg** [PerBothner/DomTerm#47]
domterm.org responds with a redirect to requests having "ru" in Accept-Language header. This redirect leads to [a spammy Russian website](http://news24-times.eversmi.com/49?source_id=35&source_site_id=&source_campaign_id=&source_teaser_id=).

Speaking in curl, here is a request with "ru":

```
$ curl "http://domterm.org/" -H "Accept-Language: ru" -v > /dev/null
<... some output omitted ...>
< HTTP/1.1 302 Found
< Date: Thu, 02 Aug 2018 18:27:47 GMT
< Server: Apache
< Location: http://news-of-wolrds.ru/06812
< Vary: Accept-Encoding
< Content-Length: 214
< Content-Type: text/html; charset=iso-8859-1
<
```

And here is request without "ru":

```
$ curl "http://domterm.org/" -H "Accept-Language: en" -v > /dev/null
<... some output omitted ...>
< HTTP/1.1 200 OK
< Date: Thu, 02 Aug 2018 18:34:43 GMT
< Server: Apache
< Last-Modified: Wed, 11 Jul 2018 23:32:58 GMT
< ETag: "2083-570c1aab75e33"
< Accept-Ranges: bytes
< Content-Length: 8323
< Vary: Accept-Encoding
< Content-Type: text/html
<
```

Thinking the problem is on my side, I've run these requests through Tor, but the behaviour persisted.

**Comment by yamnikov-oleg** [comment]
Clicking on a home page link in this repo's README results in the browser tab being instantly closed. But pasting the url directly into the address bar results in a redirect.

So I guess this behaviour changes based on the Referrer header.

**Comment by PerBothner** [comment]
There was a bad (malicious) .htaccess file. I've removed it, but there remains the question of how it got there.

**Comment by PerBothner** [comment]
The domterm.org directory in my account on DreamHost (where domterm.org is hosted) was group and world-writable.  Fixed.
