### ISSUE TITLE
documentation: link projects using DomTerm features

### ISSUE THREAD

**Issue by albertz** [PerBothner/DomTerm#59]
I think it would be useful to have a section in the documentation where you list other projects/applications/tools which make use of some of the DomTerm features.

E.g. I added text folding support now to [better_exchook](https://github.com/albertz/py_better_exchook).

**Comment by PerBothner** [comment]
I created such a page: http://domterm.org/Uses.html

Please send me a short paragraph on better_exchook and I'll add that. If you want to do it in the form of a pull request, note that the source is doc/DomTerm.texi.  I'm also happy to hand-convert plain text, Markdown, or HTML.

**Comment by albertz** [comment]
Ok, some paragraph:

> The Python [better_exchook](https://github.com/albertz/py_better_exchook) package prints stack traces with extended information such as relevant local variables. When run in DomTerm, it folds all the details of each stack frame away by default, and thus provides a much more comprehensive overview, while still providing all the details when needed.

**Comment by albertz** [comment]
Btw, I also uploaded a DomTerm screencast now to that page (see the Readme), which basically shows what I want to have with DomTerm (it kind of works, but is a bit buggy - see separate issues).

**Comment by PerBothner** [comment]
I checked in your better_exchook text and updated the website.  Thanks!

When it comes to screencasts, an alternative is a dynamic page, as in http://domterm.org/demo/nested-1.html . You just need to File -> "Save as HTML".  You can sent me the resulting html page and I can set it up on the domterm.org. (I'd probably want to link to it from the domterm sit as well.) Possibly wait until it is as polished as you'd like it, with hovering etc.  (I plan to make hovering work for saved html pages.)

**Comment by albertz** [comment]
I uploaded it [here](https://gist.githubusercontent.com/albertz/a4ce78e5ccd037041638777f10b10327/raw/7f184c01344769108fb2386db563b87588ed67db/domterm-better-exchook.html). However, when I load this directly in Chrome, it is kind of broken.

**Comment by PerBothner** [comment]
The "save as html" output isn't very nice when viewed directly, since it doesn't load the JavaScript and CSS files.  I though it more useful to just save the data.

To actually view it, you can use the `view-saved` command:

    domterm view-saved filename-or-url

(I wasn't use whether using a url would work with `view-saved` - I was gratified to see it does.)

The `view-saved` commands wraps the saved file with the needed scripts.  To create the nested-1.html page I basically did that by hand.  It might be useful to add a command to automate this.
