### ISSUE TITLE
`clear` behaves a bit buggy

### ISSUE THREAD

**Issue by albertz** [PerBothner/DomTerm#64]
I type in `clear`. Sometimes it scrolls up again, sometimes not. See the screen cast:
![domterm-clear-buggy mov](https://user-images.githubusercontent.com/59132/50679669-b55a0500-1004-11e9-9ab1-9598bb3906aa.gif)

**Comment by PerBothner** [comment]
One problem with your video is that scrollbar sometimes disappears.  Does MacOS normall hide the scrollbar when the entire output is visible? Even when `overflow-y: scroll` is specified in CSS (as it is)?  That seems a browser bug. See https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y

Aside from that, it's a little hard to see exactly when it is failing.  I  haven't been able to reproduce the problem. Do you have a sequence of actions that consistently misbehaves?

**Comment by albertz** [comment]
MacOSX normally always hides the scrollbar, unless you actually use it (i.e. you scroll around). DomTerm behaves actually normal in that respect.

**Comment by PerBothner** [comment]
_MacOSX normally always hides the scrollbar, unless you actually use it (i.e. you scroll around)._

I think that is a poor UI choice if it can't be overridden. And contrary to the HTML spec, I believe. See the link I gave:

    scroll
    Content is clipped if necessary to fit vertically in the padding box.
    Browsers display scrollbars whether or not any content is actually clipped.
    (This prevents scrollbars from appearing or disappearing when the content changes.)

It looks like space is still set aside for the scrollbars, otherwise you'd get very annoying window resizing. But if they are hidden, but space is allocated for them, then you get the confusing "why isn't the terminal using the available width" issue.

I found some links about this issue, and how to force-add the scrollbars.  For example: https://stackoverflow.com/questions/7855590/preventing-scroll-bars-from-being-hidden-for-macos-trackpad-users-in-webkit-blin/7855592

**Comment by albertz** [comment]
No, the scroll bars really should not be forced to be visible. This is really the standard MacOSX behavior, and there is no reason to override this. 

Anyway, this is also not really related to my issue report here, which is about the behavior of `clear`, and that it sometimes scroll ups and sometimes not (it doesn't matter if the scroll bars are visible or not).

**Comment by PerBothner** [comment]
_No, the scroll bars really should not be forced to be visible. This is really the standard MacOSX behavior, and there is no reason to override this._

Well, unless one thinks it's a mis-feature, which I do.  However, "fixing" it would probably be worse, especially by default.

_Anyway, this is also not really related to my issue report here, which is about the behavior of clear, and that it sometimes scroll ups and sometimes not_

Right.  I did ask:  _"I haven't been able to reproduce the problem. Do you have a sequence of actions that consistently misbehaves?"_

**Comment by albertz** [comment]
Ah sorry, I forgot to answer that one.

> I haven't been able to reproduce the problem. Do you have a sequence of actions that consistently misbehaves?

Exactly what I described, i.e. typing `clear` 2-3 times, always reproduces the problem for me. It's always the same behavior as in the screencast.

**Comment by PerBothner** [comment]
I do see some weird behavior in that sometimes the scrollbar goes blank.

It happens on both Electron and Firefox, so it's not a platform weirdness.

**Comment by PerBothner** [comment]
I checked in a fix the problem I mentioned.  Would you try again to see it that fixes your problem?

**Comment by albertz** [comment]
Ah, yes, now `clear` clears the screen + scrollbuf (which is a bit confusing to me, as this is a different behavior as I'm used to be from every other terminal emulator I have used so far) (but also, this is exactly the feature I wanted to have in #63).
I still would like to have this also as a keyboard shortcut (i.e. entry in the menu) (but also, this is #63). On Mac, Cmd+K would be a good shortcut, as this it the same in the official MacOSX Terminal. On Linux/elsewhere, I would maybe chose the same as what you have in Gnome Terminal. (Again, this is #63).
I think we can close this issue here (because there is no strange non-deterministic buggy behavior on `clear` anymore).

**Comment by PerBothner** [comment]
_"now clear clears the screen + scrollbuf (which is a bit confusing to me, as this is a different behavior as I'm used to be from every other terminal emulator I have used so far)"_

Well, DomTerm matches gnome-terminal, konsole (KDE), and venerable xterm.

_"On Linux/elsewhere, I would maybe chose the same [keyboard shortcut] as what you have in Gnome Terminal."_

Replied to at https://github.com/PerBothner/DomTerm/issues/63#issuecomment-451672291
