### ISSUE TITLE
Mouse click doesn't work with rafaelrinaldi/pure plugin of fish shell

### ISSUE THREAD

**Issue by mcarans** [PerBothner/DomTerm#70]
The [rafaelrinaldi/pure](https://github.com/rafaelrinaldi/pure) plugin of the fish shell seems to cause the mouse click functionality of DomTerm to stop working.

**Comment by PerBothner** [comment]
The default pure prompt is two lines - it has cr-lf in the middle. This confuses DomTerm.
I think this case can be handled without too much pain.  More later ...

**Comment by PerBothner** [comment]
I have a fix that works for rafaelrinaldi/pure; please try the patch below.
However, the original [sindresorhus/pure for zsh](https://github.com/sindresorhus/pure) doesn't seem to be working as I would expect; I'm looking into that.

[multiline-prompt-patch.txt](https://github.com/PerBothner/DomTerm/files/3937672/multiline-prompt-patch.txt)

**Comment by mcarans** [comment]
I tried it and it works for me - thanks a lot!
