### ISSUE TITLE
qtdomterm doesn't work with WSL

### ISSUE THREAD

**Issue by lypanov** [PerBothner/DomTerm#72]
Seeing multiple issues with WSL currently. After tackling the build / basic run issues via #69 I'm now on a new set.

Behavior:
   Starting an initial domterm results in a white screen.
   Closing this window closes the window as expected.
   Starting a *second* domterm results in a *working* domterm.
   Starting a window via qtdomterm itself in this working instance works as expected.
   However, if you close the windows at this point the only workaround for getting domterm working again is a series of killalls.

I verified that the initial domterm creates a "domterm" (not qtdomterm) process which the second qtdomterm somehow makes use of. The domterm started by the second domterm execution appears as "defunct" directly in ps.

This behavior is quite similar to what I've seen on the Mac.

**Comment by lypanov** [comment]
There is also a extremely limited set of support for emojis. Rather than using a full color font fallback I see a small set (eg, 🙂 works but fire 🔥 does not). This looks to be some deep issues with QtWebEngine on X11 so I'm going to look into getting WSL working via Electron in Windows instead as this Qt route anyway won't end well.

**Comment by PerBothner** [comment]
_"There is also an extremely limited set of support for emojis."_

This depends on the font selected.  This can be changed - see [here](http://domterm.org/Styling.html)

I did some experimentation recently, and noticed that some fonts had better Emoji support than others, without coming to a real conclusion about which is best.  I noticed that Firefox seems to do a better job using colors for Emoji than Chrome-based browsers.  I'm hoping the [Firefox site-specific browser prototype](https://bugzilla.mozilla.org/show_bug.cgi?id=1602117) soon becomes something we can use.

**Comment by PerBothner** [comment]
_"the initial domterm creates a "domterm" (not qtdomterm) process which the second qtdomterm somehow makes use of."_

Yes, it's slightly confusing.  The `qtdomterm` application really only does the browser part of domterm.  As a convenience, if you invoke `qtdomterm OPTIONS` (where `OPTIONS` does not include `--connect`) it basically just execs `domterm --qt OPTIONS`.  The latter starts  a server (if needed) and then opens a window with `qtdomterm --connect URL` (where `URL` points back to the server).

**Comment by lypanov** [comment]
Closing this issue as won't be looking into the Qt version anyway anymore. Feel free to reopen if you want to track it!
