### ISSUE TITLE
Not all URLs open as expected when ctrl-clicking them in WSL / Electron

### ISSUE THREAD

**Issue by lypanov** [PerBothner/DomTerm#74]
Open a URL command in WSL doesn't correctly quote URLs passed to cmd.exe. The correct quoting for cmd.exe is "^&" for any &s in the URL. I've hacked around it locally for the moment. Do you have any preferred string replace implementations or should I reinvent the wheel?

**Comment by PerBothner** [comment]
A partial fix might be to change `"/mnt/c/Windows/System32/cmd.exe /c start"` (in `default_browser_command` in `lws-term/server.c`) to:

    "/mnt/c/Windows/System32/cmd.exe /c start \"%U\""

However, according to [this](https://ss64.com/nt/syntax-esc.html) that doesn't handle `%` (which of course is quite common in URLs).  So we probably need some special code.

I don't have any "preferred string replace implementation" (and I want to avoid adding extra dependencies).  However, a simple loop should be trivial:

    char *ucopy = xmalloc(2*strlen(url)+1);
    char *dptr = ucopy, *sptr = url;
    char ch;
    while ((ch = *sptr++) != 0) {
        if (need_escaping(ch))
            *dptr++ = '^';
        *dptr++ = ch;
    }
    *dptr = 0;

**Comment by lypanov** [comment]
JFYI I won't get around to providing this patch as I'm no longer using DomTerm.

**Comment by PerBothner** [comment]
I checked in code to do the escaping.
