### ISSUE TITLE
build dependencies missing

### ISSUE THREAD

**Issue by nkh** [PerBothner/DomTerm#76]
Hi it seems that the dependencies you recommend installing are not found:

sudo apt-get install git gcc make automake libjson-c-dev pkg-config asciidoctor libmagic-dev zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
automake is already the newest version (1:1.16.1-1.1ubuntu1).
automake set to manually installed.
make is already the newest version (4.2.1-1.2).
pkg-config is already the newest version (0.29.1-0ubuntu2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
gcc is already the newest version (4:8.3.0-1ubuntu1.2).
git is already the newest version (1:2.19.1-1ubuntu1.1).
The following packages were automatically installed and are no longer required:
  libc6-dev:i386 libncurses-dev:i386 libncursesw5 libtinfo5 linux-libc-dev:i386 python-lzma python-parsley python-psutil python-twisted python-txsocksx python-wicd
  python3-dateutil python3-pycountry python3-streamlink python3-websocket streamlink
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  ruby-asciidoctor
The following NEW packages will be installed:
  asciidoctor libjson-c-dev libmagic-dev ruby-asciidoctor
0 upgraded, 4 newly installed, 0 to remove and 4 not upgraded.
Need to get 278 kB/310 kB of archives.
After this operation, 1,631 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Ign:1 http://se.archive.ubuntu.com/ubuntu cosmic/universe amd64 ruby-asciidoctor all 1.5.7.1-1
Err:2 http://se.archive.ubuntu.com/ubuntu cosmic/universe amd64 asciidoctor amd64 1.5.7.1-1
  404  Not Found [IP: 194.71.11.165 80]
Ign:3 http://se.archive.ubuntu.com/ubuntu cosmic-updates/main amd64 libmagic-dev amd64 1:5.34-2ubuntu0.1
Err:1 http://se.archive.ubuntu.com/ubuntu cosmic/universe amd64 ruby-asciidoctor all 1.5.7.1-1
  404  Not Found [IP: 194.71.11.165 80]
Err:3 http://security.ubuntu.com/ubuntu cosmic-updates/main amd64 libmagic-dev amd64 1:5.34-2ubuntu0.1
  404  Not Found [IP: 194.71.11.165 80]
Unable to correct missing packages.
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/universe/a/asciidoctor/ruby-asciidoctor_1.5.7.1-1_all.deb  404  Not Found [IP: 194.71.11.165 80]
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/universe/a/asciidoctor/asciidoctor_1.5.7.1-1_amd64.deb  404  Not Found [IP: 194.71.11.165 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic-dev_5.34-2ubuntu0.1_amd64.deb  404  Not Found [IP: 194.71.11.165 80]
E: Aborting install.

**Comment by PerBothner** [comment]
That looks like either a networking problem, or bad package configuration, or a corrupted package index/repository.  I.e. nothing specifically relating to DomTerm.
I notice that for example `http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic-dev_5.34-2ubuntu0.1_amd64.deb` is missing - but the same directory has both older and newer versions.  Perhaps that version was removed because of some security issue?
I don't use Debian or Ubuntu frequently, but you could try first running:

     sudo apt update
     sudo apt upgrade

and possibly replace the suggested `apt-get` command with the newer `apt`.

Worst case the problem packages seem to be related to asciidoctor and libmagic, which are both optional.

**Comment by nkh** [comment]
I'll dig a bit deeper and build without them to test if necessary. Thank you for the prompt answer.

**Comment by nkh** [comment]
I run in this error, any idea?

19 ~/3/DomTerm ■ autoconf -i
configure.ac:4: error: possibly undefined macro: AM_MAINTAINER_MODE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:87: error: possibly undefined macro: AM_CONDITIONAL
20 ~/3/DomTerm ■ ./configure
./configure: line 1976: syntax error near unexpected token `enable'
./configure: line 1976: `AM_MAINTAINER_MODE(enable)'

**Comment by PerBothner** [comment]
`configure.ac:4: error: possibly undefined macro: AM_MAINTAINER_MODE`

Probably because you haven't run `aclocal`,  This should have been done automatically if you followed the instructions and ran:

     autoreconf -i
