### ISSUE TITLE
FYI for docs

### ISSUE THREAD

**Issue by dankilman** [PerBothner/DomTerm#81]
Just tried building from source on macOS.
It seems that libwebsockets that comes with brew is v >= 4 which seems incompatible, got `ld` failing on some linking.
Downgraded to `3.2.2` and build was successful

**Comment by PerBothner** [comment]
Does it seem to be related to [this issue](https://github.com/Homebrew/homebrew-core/issues/50074)?

**Comment by dankilman** [comment]
It looked like a different thing. Some reference to and symbol starting with `_lws` was missing I think.
I can reinstall libwebsockets >=4 and send the exact error

**Comment by PerBothner** [comment]
I'm getting that `lws_extension_callback_pm_deflate` is missing.  Looking into it.

**Comment by PerBothner** [comment]
I may have fixed the problem:  It seems to build ok with the brew-supplied libwebsockets now.

**Comment by PerBothner** [comment]
Could you confirm this problem is fixed?

**Comment by dankilman** [comment]
Still getting the same error as before
```
gcc -I/usr/local/Cellar/openssl@1.1/1.1.1g/include -I/usr/local/Cellar/json-c/0.13.1/include/json-c -I/usr/local/include -I./lws-term -I/usr/local/Cellar/libwebsockets/4.0.19/include  -DCOMPILED_IN_RESOURCES  -g -O2   -o ldomterm ldomterm-server.o ldomterm-utils.o ldomterm-protocol.o ldomterm-http.o ldomterm-whereami.o ldomterm-commands.o ldomterm-command-connect.o ldomterm-help.o ldomterm-junzip.o ldomterm-settings.o ldomterm-git-describe.o ldomterm-resources.o -L/usr/local/Cellar/libwebsockets/4.0.19/lib -lwebsockets -L/usr/local/Cellar/openssl@1.1/1.1.1g/lib -lssl -lcrypto -L/usr/local/Cellar/json-c/0.13.1/lib -ljson-c  -lpthread -lutil -lz
Undefined symbols for architecture x86_64:
  "_lws_extension_callback_pm_deflate", referenced from:
      _extensions in ldomterm-server.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [ldomterm] Error 1
make: *** [all-recursive] Error 1
```

**Comment by dankilman** [comment]
scratch my last comment, i forgot to pull the recent changes :)
it builds successfully now
