### ISSUE TITLE
Attaching to a session does not work.

### ISSUE THREAD

**Issue by lockywolf** [PerBothner/DomTerm#85]
Hello.

My use scenario is the following:

```
lockywolf@delllaptop:/tmp$ domterm
lockywolf@delllaptop:/tmp$ domterm list
pid: -1, session#: 1, #windows: 0
lockywolf@delllaptop:/tmp$ domterm attach 1
no session '1' found 
lockywolf@delllaptop:/tmp$ pgrep -a domterm
21316 domterm
lockywolf@delllaptop:/tmp$ 
```

So domterm is running, but there seems to be no obvious way to connect to it.

Slackware-current, domterm 2.1, build config:

```
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --with-libwebsockets \
  --with-asciidoctor \
  --with-javafx \
  --with-qtwebengine \
  --build=$ARCH-slackware-linux || exit 1

lockywolf@delllaptop:/tmp$ java -version
Picked up _JAVA_OPTIONS:  -Dsun.java2d.uiScale=1.35 -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (Slackware)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

```

**Comment by PerBothner** [comment]
Running `domterm`  with no arguments is supposed to create a new terminal window.  It it doesn't, something is configured/installed wrong. Try leaving off the `make install` and just run in-place - and try the --firefox argument:

    ./configure ...whatever...
    make
    bin/domterm --firefox

If that works, you can try

    bin/domterm --electron   # if electron is in your PATH
    bin/domterm --webview # if configured --with-webview

What I normally do is:

    ./configure --prefix=/some/path
    make
    make install

Then somewhere in your path create a symlink to `/some/path/bin/domterm`

**Comment by lockywolf** [comment]
Duplicate of #86
