### ISSUE TITLE
Fix prompt colours

### ISSUE THREAD

**Issue by mcarans** [PerBothner/DomTerm#89]
My prompt is set up using a bash-it theme called [brainy](https://github.com/Bash-it/bash-it/blob/master/themes/brainy/brainy.theme.bash). Even though the standard terminal and DomTerm are set up with a black background, the prompt colours are different in DomTerm to the terminal. Most are just changes in shade, but the first part changes from red in a terminal to blue in DomTerm. I guess DomTerm overrides the colours. How can I keep the theme's original colours?

I found the colours in DomTerm are reset to be closer to the terminal so that they only differ in shade if I "sudo bash" and then "exit" which is weird.

**Comment by mcarans** [comment]
I realised the prompt colours chaneg with sudo in both terminal and DomTerm - sorry for confusion, closing.

**Comment by PerBothner** [comment]
No problem.  I generally prefer a light theme, so I mostly tweak the light-theme colors to my taste (and monitors).  The Domterm defaults could probably do with some tweaking when it does to dark mode.
