### ISSUE TITLE
New terminal tab gives "Connection to backend lost Too may failures (error code 1006)..." attempting WebSockets connection to backend server."

### ISSUE THREAD

**Issue by mcarans** [PerBothner/DomTerm#91]
When I choose the File->New terminal tab menu (or New Window), I get "Connection to backend lost Too may failures (error code 1006) attempting WebSockets connection to backend server." This also stops the first tab from working properly.

domterm status:

```
DomTerm version 2.9.0 (git describe: 2.1-367-g0e0c2a2)
Copyright 2021 Per Bothner and others
Using Libwebsockets 3.2.0
Reading settings from: /home/mcarans/.config/domterm/settings.ini
Backend pid:2376 command-socket:/run/user/1000/domterm/default.socket
Window 1:  qtwebengine: 5.12.8, chrome: 69.0.3497.128
  session#1: pid: 2421, tty: /dev/pts/0
```

**Comment by PerBothner** [comment]
Hm. I'm not seeing that.  I just tested it.  Could be due to the relatively old version of libwebsockets.  I get:

    Using Libwebsockets 4.1.99-v4.1.0-112-g773b5490

Would you mind trying to clone and build libwebsockets, as in the instructions?

**Comment by mcarans** [comment]
I tried but got some build errors whic hI've put in this issue: https://github.com/PerBothner/DomTerm/issues/92

**Comment by mcarans** [comment]
I still get the error with new libwebsockets

```
DomTerm version 2.9.0 (git describe: 2.1-385-gf1be77b)
Copyright 2021 Per Bothner and others
Using Libwebsockets 4.1.99-v4.1.0-214-geb567cf7
Reading settings from: /home/mcarans/.config/domterm/settings.ini
Backend pid:18605 command-socket:/run/user/1000/domterm/default.socket
Window 1:  qtwebengine: 5.12.8, chrome: 69.0.3497.128
  session#1: pid: 18652, tty: /dev/pts/0
```

**Comment by mcarans** [comment]
Fixed with newer libwebsockets
